# -*- coding: utf-8 -*-
"""Project: 1 MADLIBS_Python Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flm9VPH1WAQM0v7qI26OPDybX4qIBzdl
"""

#MADLIBS_Projectcc
#my first MADLIBS project


name = input ("Ali")
adjective_1 = input ("exited")
place = input ("amuesement park")
adjective_2 = input ("amazing")
animal = input ("cat")
verb_1 = input ("jumping")
name_2 = input ("ali")
exclamation =input ("Wow!")
person =input ("best friend")
verb_2 = input ("swinging")
activity = input ("football ke sath khela")
food =input ("pizza")
print(f"""
aik din {name} {adjective_1} tha , wo {place} gya aur {adjective_2} rides karny laga,
achanak us ne ik {animal} dekhi jo {verb_1} kr rhi thi {name_2} ne use dekh kar fauran kaha {exclamation} isi doran uska {person} agya
or us ny kaha mn to samjha tm {verb_2} kar rhy hogy is k bad dono ne mil ker {activity}  or apna {food} enjoy kia.
""")